require 'yaml'
require 'date'
require 'bundler/setup'
require 'pry'
require 'colorize'

require_relative './modules/database'
require_relative './modules/input-output'
require_relative './modules/search_engine'
require_relative './modules/statistics'
require_relative './classes/cars_management'
