require 'yaml'
require 'date'
require 'bundler/setup'
require 'terminal-table'
require 'colorize'
require 'i18n'
require 'pry'

require_relative './database'
require_relative './modules/input-output'
require_relative './search_engine_query'
require_relative './statistics'
require_relative './modules/validation'
require_relative './cars_management'
